In [3]:
import pandas as pd

import requests as re
import json 
from IPython.display import JSON

In [4]:
from config import ApiKey

In [3]:
df = pd.read_csv('Heavy_Data/flightsprocessed.csv')

In [6]:
dates = pd.to_datetime(df['fl_date'])

In [7]:
df['fl_date_previous'] = dates -  pd.to_timedelta((7), unit='d')

In [9]:
df.nunique()

Unnamed: 0                         684223
fl_date                               730
mkt_unique_carrier                     11
branded_code_share                     16
mkt_carrier                            11
mkt_carrier_fl_num                   7058
op_unique_carrier                      28
tail_num                             6419
op_carrier_fl_num                    7067
origin_airport_id                     375
origin                                375
origin_city_name                      367
dest_airport_id                       375
dest                                  375
dest_city_name                        367
crs_dep_time                         1349
dep_time                             1425
dep_delay                            1060
taxi_out                              171
wheels_off                           1400
wheels_on                            1440
taxi_in                               155
crs_arr_time                         1414
arr_time                             1440
arr_delay                            1086
cancelled                               1
diverted                                1
dup                                     1
crs_elapsed_time                      585
actual_elapsed_time                   640
air_time                              620
flights                                 1
distance                             1594
carrier_delay                         806
weather_delay                         485
nas_delay                             496
security_delay                         86
late_aircraft_delay                   592
first_dep_time                       1082
total_add_gtime                       181
longest_add_gtime                     173
month                                  12
hour                                   24
haul                                    3
flight_speed                        51320
state                                  53
proportional_activity                 304
dummydelay                              2
route                                6638
mean delay for route                 5502
mean delay based on air carrier        11
fl_date_previous                      730
dtype: int64

In [79]:
Test = pd.DataFrame.sample(df,910)

In [262]:
weather_data.isnull().sum().sort_values(ascending=False)

longest_add_gtime     905
total_add_gtime       905
first_dep_time        905
nas_delay             728
carrier_delay         728
                     ...
op_carrier_fl_num       0
mkt_unique_carrier      0
tail_num                0
op_unique_carrier       0
fl_date                 0
Length: 68, dtype: int64

In [13]:
pd.set_option('display.max_columns', None)

In [25]:
df

,Unnamed: 0,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,month,hour,haul,flight_speed,state,proportional_activity,dummydelay,route,mean delay for route,mean delay based on air carrier,fl_date_previous
0,0,2018-06-15,DL,DL_CODESHARE,DL,6230,G7,N378CA,6230,14492,RDU,"Raleigh/Durham, NC",11042,CLE,"Cleveland, OH",1942,1958.0,16.0,28.0,2026.0,2132.0,6.0,2124,2138.0,14.0,0.0,0.0,N,102.0,100.0,66.0,1.0,416.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,20,Short,378.181818,OH,0.008601,1,RDUCLE,24.321429,2.490683,2018-06-08
1,1,2019-07-30,DL,DL_CODESHARE,DL,6229,G7,N186GJ,6229,14492,RDU,"Raleigh/Durham, NC",11042,CLE,"Cleveland, OH",2049,2047.0,-2.0,24.0,2111.0,2214.0,5.0,2233,2219.0,-14.0,0.0,0.0,N,104.0,92.0,63.0,1.0,416.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,21,Short,396.190476,OH,0.008601,0,RDUCLE,24.321429,2.490683,2019-07-23
2,2,2018-07-17,DL,DL_CODESHARE,DL,6234,G7,N354CA,6234,14492,RDU,"Raleigh/Durham, NC",11042,CLE,"Cleveland, OH",2059,2234.0,95.0,22.0,2256.0,2.0,11.0,2237,13.0,96.0,0.0,0.0,N,98.0,99.0,66.0,1.0,416.0,0.0,0.0,4.0,0.0,92.0,NaN,NaN,NaN,7,22,Short,378.181818,OH,0.008601,1,RDUCLE,24.321429,2.490683,2018-07-10
3,3,2019-08-04,DL,DL_CODESHARE,DL,6229,G7,N186GJ,6229,14492,RDU,"Raleigh/Durham, NC",11042,CLE,"Cleveland, OH",2049,2039.0,-10.0,20.0,2059.0,2158.0,5.0,2233,2203.0,-30.0,0.0,0.0,N,104.0,84.0,59.0,1.0,416.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,20,Short,423.050847,OH,0.008601,0,RDUCLE,24.321429,2.490683,2019-07-28
4,4,2019-05-30,DL,DL_CODESHARE,DL,6229,G7,N331CA,6229,14492,RDU,"Raleigh/Durham, NC",11042,CLE,"Cleveland, OH",2030,2021.0,-9.0,25.0,2046.0,2152.0,16.0,2213,2208.0,-5.0,0.0,0.0,N,103.0,107.0,66.0,1.0,416.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,20,Short,378.181818,OH,0.008601,0,RDUCLE,24.321429,2.490683,2019-05-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684218,684218,2018-01-15,HA,HA,HA,466,HA,N588HA,466,14222,PPG,"Pago Pago, TT",12173,HNL,"Honolulu, HI",2330,2349.0,19.0,17.0,6.0,613.0,7.0,600,620.0,20.0,0.0,0.0,N,330.0,331.0,307.0,1.0,2599.0,8.0,0.0,0.0,0.0,12.0,NaN,NaN,NaN,1,6,Long,507.947883,HI,0.000015,1,PPGHNL,68.200000,0.178935,2018-01-08
684219,684219,2018-09-24,HA,HA,HA,466,HA,N380HA,466,14222,PPG,"Pago Pago, TT",12173,HNL,"Honolulu, HI",2320,2307.0,-13.0,15.0,2322.0,532.0,8.0,550,540.0,-10.0,0.0,0.0,N,330.0,333.0,310.0,1.0,2599.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,23,Long,503.032258,HI,0.000015,0,PPGHNL,68.200000,0.178935,2018-09-17
684220,684220,2019-07-08,HA,HA,HA,466,HA,N381HA,466,14222,PPG,"Pago Pago, TT",12173,HNL,"Honolulu, HI",2320,2325.0,5.0,14.0,2339.0,608.0,58.0,550,706.0,76.0,0.0,0.0,N,330.0,401.0,329.0,1.0,2599.0,71.0,0.0,0.0,0.0,5.0,NaN,NaN,NaN,7,23,Long,473.981763,HI,0.000015,1,PPGHNL,68.200000,0.178935,2019-07-01
684221,684221,2019-05-09,HA,HA,HA,466,HA,N370HA,466,14222,PPG,"Pago Pago, TT",12173,HNL,"Honolulu, HI",2320,2309.0,-11.0,15.0,2324.0,521.0,10.0,545,531.0,-14.0,0.0,0.0,N,325.0,322.0,297.0,1.0,2599.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,23,Long,525.050505,HI,0.000015,0,PPGHNL,68.200000,0.178935,2019-05-02
684222,684222,2019-02-04,HA,HA,HA,466,HA,N391HA,466,14222,PPG,"Pago Pago, TT",12173,HNL,"Honolulu, HI",2325,10.0,45.0,14.0,24.0,620.0,8.0,550,628.0,38.0,0.0,0.0,N,325.0,318.0,296.0,1.0,2599.0,0.0,26.0,0.0,0.0,12.0,NaN,NaN,NaN,2,24,Long,526.824324,HI,0.000015,1,PPGHNL,68.200000,0.178935,2019-01-28

In [36]:
Z = [df.fl_date.unique(),df.fl_date_previous.unique()]

In [37]:
Z = pd.DataFrame(Z)

In [39]:
Z = Z.T

In [41]:
Z.columns = ['fl_date','fl_date_previous']

In [43]:
X1 = df[['fl_date','origin_city_name']]

In [45]:
X1.sort_values(by='fl_date')

           fl_date                origin_city_name
633269  2018-01-01  West Palm Beach/Palm Beach, FL
666606  2018-01-01                    San Jose, CA
409276  2018-01-01                       Miami, FL
110702  2018-01-01                  Pittsburgh, PA
490713  2018-01-01                      Newark, NJ
...            ...                             ...
382564  2019-12-31                     Chicago, IL
474987  2019-12-31                      Denver, CO
57104   2019-12-31                   St. Louis, MO
584581  2019-12-31                       Aspen, CO
195498  2019-12-31                  Cincinnati, OH

[684223 rows x 2 columns]

In [49]:
X2 = X1.sample(1000)

In [52]:
X2.head()

           fl_date  origin_city_name
440901  2019-11-06    Louisville, KY
401556  2018-07-16  Philadelphia, PA
366334  2019-09-14       Phoenix, AZ
302766  2018-07-31     Charlotte, NC
655931  2019-06-01          Reno, NV

In [55]:
X1['add'] = X1['fl_date'] + X1['origin_city_name']

In [56]:
X1

           fl_date    origin_city_name                           add
0       2018-06-15  Raleigh/Durham, NC  2018-06-15Raleigh/Durham, NC
1       2019-07-30  Raleigh/Durham, NC  2019-07-30Raleigh/Durham, NC
2       2018-07-17  Raleigh/Durham, NC  2018-07-17Raleigh/Durham, NC
3       2019-08-04  Raleigh/Durham, NC  2019-08-04Raleigh/Durham, NC
4       2019-05-30  Raleigh/Durham, NC  2019-05-30Raleigh/Durham, NC
...            ...                 ...                           ...
684218  2018-01-15       Pago Pago, TT       2018-01-15Pago Pago, TT
684219  2018-09-24       Pago Pago, TT       2018-09-24Pago Pago, TT
684220  2019-07-08       Pago Pago, TT       2019-07-08Pago Pago, TT
684221  2019-05-09       Pago Pago, TT       2019-05-09Pago Pago, TT
684222  2019-02-04       Pago Pago, TT       2019-02-04Pago Pago, TT

[684223 rows x 3 columns]

In [57]:
X1['add'].nunique()

115727

In [71]:
X1['test'] = X1['fl_date'].apply(lambda x: x[:7])

<ipython-input-71-62dceb6b26bd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X1['test'] = X1['fl_date'].apply(lambda x: x[:7])

In [73]:
X1['test'] = X1['test'].apply(lambda x: x+'-15')

<ipython-input-73-a5347ac2f457>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X1['test'] = X1['test'].apply(lambda x: x+'-15')

In [75]:
X1['add'] = X1['test'] + X1['origin_city_name']

<ipython-input-75-ae6073b916a5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X1['add'] = X1['test'] + X1['origin_city_name']

In [76]:
X1['add'].nunique()

8200

In [63]:
X1.dtypes

fl_date             object
origin_city_name    object
add                 object
test                object
dtype: object

In [81]:
Test

,Unnamed: 0,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,month,hour,haul,flight_speed,state,proportional_activity,dummydelay,route,mean delay for route,mean delay based on air carrier,fl_date_previous
671530,671530,2018-09-23,AS,AS_CODESHARE,AS,2084,QX,N436QX,2084,13264,MFR,"Medford, OR",14057,PDX,"Portland, OR",1935,1927.0,-8.0,11.0,1938.0,2024.0,7.0,2032,2031.0,-1.0,0.0,0.0,N,57.0,64.0,46.0,1.0,222.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,19,Short,289.565217,OR,0.001152,0,MFRPDX,-1.303665,0.429957,2018-09-16
576677,576677,2019-09-08,UA,UA_CODESHARE,UA,3923,ZW,N426AW,3923,10257,ALB,"Albany, NY",12264,IAD,"Washington, DC",1445,1439.0,-6.0,9.0,1448.0,1549.0,3.0,1618,1552.0,-26.0,0.0,0.0,N,93.0,73.0,61.0,1.0,325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,14,Short,319.672131,DC,0.002162,0,ALBIAD,19.194805,9.017267,2019-09-01
458132,458132,2019-12-30,AA,AA_CODESHARE,AA,3413,MQ,N220NN,3413,12992,LIT,"Little Rock, AR",11298,DFW,"Dallas/Fort Worth, TX",2013,2016.0,3.0,21.0,2037.0,2141.0,9.0,2141,2150.0,9.0,0.0,0.0,N,88.0,94.0,64.0,1.0,304.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,20,Short,285.000000,TX,0.001865,1,LITDFW,7.461538,6.393277,2019-12-23
324870,324870,2018-01-31,AA,AA_CODESHARE,AA,4760,YX,N403YX,4760,11278,DCA,"Washington, DC",12953,LGA,"New York, NY",1900,1854.0,-6.0,33.0,1927.0,2011.0,13.0,2039,2024.0,-15.0,0.0,0.0,N,99.0,90.0,44.0,1.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,19,Short,291.818182,NY,0.017513,0,DCALGA,13.448276,6.393277,2018-01-24
504388,504388,2018-06-13,UA,UA_CODESHARE,UA,5539,OO,N144SY,5539,14771,SFO,"San Francisco, CA",14869,SLC,"Salt Lake City, UT",900,855.0,-5.0,17.0,912.0,1141.0,5.0,1202,1146.0,-16.0,0.0,0.0,N,122.0,111.0,89.0,1.0,599.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,9,Short,403.820225,UT,0.022608,0,SFOSLC,7.478386,9.017267,2018-06-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218259,218259,2019-12-20,WN,WN,WN,2084,WN,N712SW,2084,10821,BWI,"Baltimore, MD",10693,BNA,"Nashville, TN",1920,1942.0,22.0,13.0,1955.0,2031.0,4.0,2015,2035.0,20.0,0.0,0.0,N,115.0,113.0,96.0,1.0,587.0,15.0,0.0,0.0,0.0,5.0,NaN,NaN,NaN,12,19,Short,366.875000,TN,0.013186,1,BWIBNA,-0.552486,3.444016,2019-12-13
250443,250443,2018-07-15,WN,WN,WN,3149,WN,N937WN,3149,14893,SMF,"Sacramento, CA",15016,STL,"St. Louis, MO",910,905.0,-5.0,10.0,915.0,1433.0,3.0,1445,1436.0,-9.0,0.0,0.0,N,215.0,211.0,198.0,1.0,1679.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,9,Medium,508.787879,MO,0.006941,0,SMFSTL,-3.720000,3.444016,2018-07-08
354329,354329,2018-08-09,AA,AA,AA,2042,AA,N973UY,2042,14771,SFO,"San Francisco, CA",14107,PHX,"Phoenix, AZ",550,549.0,-1.0,12.0,601.0,736.0,16.0,758,752.0,-6.0,0.0,0.0,N,128.0,123.0,95.0,1.0,651.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,6,Short,411.157895,AZ,0.022608,0,SFOPHX,7.534632,6.393277,2018-08-02
573121,573121,2019-12-08,UA,UA_CODESHARE,UA,4552,G7,N153GJ,4552,12451,JAX,"Jacksonville, FL",13930,ORD,"Chicago, IL",730,727.0,-3.0,29.0,756.0,900.0,7.0,912,907.0,-5.0,0.0,0.0,N,162.0,160.0,124.0,1.0,864.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,7,Short,418.064516,IL,0.004443,0,JAXORD,3.946524,9.017267,2019-12-01
351445,351445,2019-05-25,AA,AA_CODESHARE,AA,4035,MQ,N271NN,4035,11298,DFW,"Dallas/Fort Worth, TX",11003,CID,"Cedar Rapids/Iowa City, IA",1030,1024.0,-6.0,13.0,1037.0,1209.0,6.0,1232,1215.0,-17.0,0.0,0.0,N,122.0,111.0,92.0,1.0,685.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,10,Short,446.739130,IA,0.036820,0,DFWCID,0.500000,6.393277,2019-05-18

In [82]:
random = Test[:10]

In [83]:
random

,Unnamed: 0,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,month,hour,haul,flight_speed,state,proportional_activity,dummydelay,route,mean delay for route,mean delay based on air carrier,fl_date_previous
671530,671530,2018-09-23,AS,AS_CODESHARE,AS,2084,QX,N436QX,2084,13264,MFR,"Medford, OR",14057,PDX,"Portland, OR",1935,1927.0,-8.0,11.0,1938.0,2024.0,7.0,2032,2031.0,-1.0,0.0,0.0,N,57.0,64.0,46.0,1.0,222.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,19,Short,289.565217,OR,0.001152,0,MFRPDX,-1.303665,0.429957,2018-09-16
576677,576677,2019-09-08,UA,UA_CODESHARE,UA,3923,ZW,N426AW,3923,10257,ALB,"Albany, NY",12264,IAD,"Washington, DC",1445,1439.0,-6.0,9.0,1448.0,1549.0,3.0,1618,1552.0,-26.0,0.0,0.0,N,93.0,73.0,61.0,1.0,325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,14,Short,319.672131,DC,0.002162,0,ALBIAD,19.194805,9.017267,2019-09-01
458132,458132,2019-12-30,AA,AA_CODESHARE,AA,3413,MQ,N220NN,3413,12992,LIT,"Little Rock, AR",11298,DFW,"Dallas/Fort Worth, TX",2013,2016.0,3.0,21.0,2037.0,2141.0,9.0,2141,2150.0,9.0,0.0,0.0,N,88.0,94.0,64.0,1.0,304.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,20,Short,285.000000,TX,0.001865,1,LITDFW,7.461538,6.393277,2019-12-23
324870,324870,2018-01-31,AA,AA_CODESHARE,AA,4760,YX,N403YX,4760,11278,DCA,"Washington, DC",12953,LGA,"New York, NY",1900,1854.0,-6.0,33.0,1927.0,2011.0,13.0,2039,2024.0,-15.0,0.0,0.0,N,99.0,90.0,44.0,1.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,19,Short,291.818182,NY,0.017513,0,DCALGA,13.448276,6.393277,2018-01-24
504388,504388,2018-06-13,UA,UA_CODESHARE,UA,5539,OO,N144SY,5539,14771,SFO,"San Francisco, CA",14869,SLC,"Salt Lake City, UT",900,855.0,-5.0,17.0,912.0,1141.0,5.0,1202,1146.0,-16.0,0.0,0.0,N,122.0,111.0,89.0,1.0,599.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,9,Short,403.820225,UT,0.022608,0,SFOSLC,7.478386,9.017267,2018-06-06
83739,83739,2018-12-09,DL,DL_CODESHARE,DL,5906,YX,N215JQ,5906,11066,CMH,"Columbus, OH",12478,JFK,"New York, NY",1758,1755.0,-3.0,17.0,1812.0,1936.0,14.0,2005,1950.0,-15.0,0.0,0.0,N,127.0,115.0,84.0,1.0,483.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,18,Short,345.000000,NY,0.006125,0,CMHJFK,-0.336449,2.490683,2018-12-02
85375,85375,2018-01-14,DL,DL_CODESHARE,DL,6059,YX,N216JQ,6059,10721,BOS,"Boston, MA",12953,LGA,"New York, NY",1000,950.0,-10.0,21.0,1011.0,1055.0,4.0,1133,1059.0,-34.0,0.0,0.0,N,93.0,69.0,44.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,Short,250.909091,NY,0.018905,0,BOSLGA,8.193511,2.490683,2018-01-07
491929,491929,2018-11-02,UA,UA_CODESHARE,UA,4941,C5,N14186,4941,11618,EWR,"Newark, NJ",13244,MEM,"Memphis, TN",1940,1934.0,-6.0,24.0,1958.0,2150.0,6.0,2153,2156.0,3.0,0.0,0.0,N,193.0,202.0,172.0,1.0,946.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,19,Short,330.000000,TN,0.019901,0,EWRMEM,25.009804,9.017267,2018-10-26
275868,275868,2019-12-09,WN,WN,WN,2575,WN,N8638A,2575,13232,MDW,"Chicago, IL",11292,DEN,"Denver, CO",1730,1745.0,15.0,11.0,1756.0,1909.0,10.0,1905,1919.0,14.0,0.0,0.0,N,155.0,154.0,133.0,1.0,895.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,17,Short,403.759398,CO,0.010570,1,MDWDEN,3.403846,3.444016,2019-12-02
484971,484971,2019-09-22,UA,UA_CODESHARE,UA,3503,YX,N651RW,3503,11618,EWR,"Newark, NJ",11433,DTW,"Detroit, MI",1400,1446.0,46.0,16.0,1502.0,1622.0,13.0,1557,1635.0,38.0,0.0,0.0,N,117.0,109.0,80.0,1.0,488.0,9.0,0.0,0.0,0.0,29.0,NaN,NaN,NaN,9,15,Short,366.000000,MI,0.019901,1,EWRDTW,2.369620,9.017267,2019-09-15

In [19]:
weather = re.get(f'https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/weatherdata/history?aggregateHours=24&combinationMethod=aggregate&startDateTime=2018-06-08T00%3A00%3A00&endDateTime=2018-06-15T00%3A00%3A00&maxStations=-1&maxDistance=-1&contentType=json&unitGroup=metric&locationMode=single&key={ApiKey}&dataElements=default&',params=params)

In [151]:
weather1 = re.get(f'https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/weatherdata/history?aggregateHours=24&combinationMethod=aggregate&maxStations=-1&maxDistance=-1&contentType=json&unitGroup=metric&locationMode=single&key={ApiKey}&dataElements=default&',params=params)

Trying out different permutations

In [152]:
JSON(weather1.json())

In [150]:
params = {'location': 'Albany, NY','startDateTime':'2018-09-16','endDateTime':'2018-09-23'}

In [102]:
weather1

In [139]:
i = []

In [166]:
random.reset_index(inplace=True)

In [190]:
e = random['fl_date_previous'][0]

In [191]:
from datetime import datetime

In [207]:
random['fl_date'][0]

'2018-09-23'

In [210]:
random['fl_date0'] = random['fl_date_previous'].apply(lambda x: x.date().strftime('%Y-%m-%d'))

<ipython-input-210-18416fcdebbb>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  random['fl_date0'] = random['fl_date_previous'].apply(lambda x: x.date().strftime('%Y-%m-%d'))

In [211]:
random

,index,Unnamed: 0,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,month,hour,haul,flight_speed,state,proportional_activity,dummydelay,route,mean delay for route,mean delay based on air carrier,fl_date_previous,conditions,fl_date0
0,671530,671530,2018-09-23,AS,AS_CODESHARE,AS,2084,QX,N436QX,2084,13264,MFR,"Medford, OR",14057,PDX,"Portland, OR",1935,1927.0,-8.0,11.0,1938.0,2024.0,7.0,2032,2031.0,-1.0,0.0,0.0,N,57.0,64.0,46.0,1.0,222.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,19,Short,289.565217,OR,0.001152,0,MFRPDX,-1.303665,0.429957,2018-09-16,None,2018-09-16
1,576677,576677,2019-09-08,UA,UA_CODESHARE,UA,3923,ZW,N426AW,3923,10257,ALB,"Albany, NY",12264,IAD,"Washington, DC",1445,1439.0,-6.0,9.0,1448.0,1549.0,3.0,1618,1552.0,-26.0,0.0,0.0,N,93.0,73.0,61.0,1.0,325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,14,Short,319.672131,DC,0.002162,0,ALBIAD,19.194805,9.017267,2019-09-01,None,2019-09-01
2,458132,458132,2019-12-30,AA,AA_CODESHARE,AA,3413,MQ,N220NN,3413,12992,LIT,"Little Rock, AR",11298,DFW,"Dallas/Fort Worth, TX",2013,2016.0,3.0,21.0,2037.0,2141.0,9.0,2141,2150.0,9.0,0.0,0.0,N,88.0,94.0,64.0,1.0,304.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,20,Short,285.000000,TX,0.001865,1,LITDFW,7.461538,6.393277,2019-12-23,None,2019-12-23
3,324870,324870,2018-01-31,AA,AA_CODESHARE,AA,4760,YX,N403YX,4760,11278,DCA,"Washington, DC",12953,LGA,"New York, NY",1900,1854.0,-6.0,33.0,1927.0,2011.0,13.0,2039,2024.0,-15.0,0.0,0.0,N,99.0,90.0,44.0,1.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,19,Short,291.818182,NY,0.017513,0,DCALGA,13.448276,6.393277,2018-01-24,None,2018-01-24
4,504388,504388,2018-06-13,UA,UA_CODESHARE,UA,5539,OO,N144SY,5539,14771,SFO,"San Francisco, CA",14869,SLC,"Salt Lake City, UT",900,855.0,-5.0,17.0,912.0,1141.0,5.0,1202,1146.0,-16.0,0.0,0.0,N,122.0,111.0,89.0,1.0,599.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,9,Short,403.820225,UT,0.022608,0,SFOSLC,7.478386,9.017267,2018-06-06,None,2018-06-06
5,83739,83739,2018-12-09,DL,DL_CODESHARE,DL,5906,YX,N215JQ,5906,11066,CMH,"Columbus, OH",12478,JFK,"New York, NY",1758,1755.0,-3.0,17.0,1812.0,1936.0,14.0,2005,1950.0,-15.0,0.0,0.0,N,127.0,115.0,84.0,1.0,483.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,18,Short,345.000000,NY,0.006125,0,CMHJFK,-0.336449,2.490683,2018-12-02,None,2018-12-02
6,85375,85375,2018-01-14,DL,DL_CODESHARE,DL,6059,YX,N216JQ,6059,10721,BOS,"Boston, MA",12953,LGA,"New York, NY",1000,950.0,-10.0,21.0,1011.0,1055.0,4.0,1133,1059.0,-34.0,0.0,0.0,N,93.0,69.0,44.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,Short,250.909091,NY,0.018905,0,BOSLGA,8.193511,2.490683,2018-01-07,None,2018-01-07
7,491929,491929,2018-11-02,UA,UA_CODESHARE,UA,4941,C5,N14186,4941,11618,EWR,"Newark, NJ",13244,MEM,"Memphis, TN",1940,1934.0,-6.0,24.0,1958.0,2150.0,6.0,2153,2156.0,3.0,0.0,0.0,N,193.0,202.0,172.0,1.0,946.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,19,Short,330.000000,TN,0.019901,0,EWRMEM,25.009804,9.017267,2018-10-26,None,2018-10-26
8,275868,275868,2019-12-09,WN,WN,WN,2575,WN,N8638A,2575,13232,MDW,"Chicago, IL",11292,DEN,"Denver, CO",1730,1745.0,15.0,11.0,1756.0,1909.0,10.0,1905,1919.0,14.0,0.0,0.0,N,155.0,154.0,133.0,1.0,895.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,17,Short,403.759398,CO,0.010570,1,MDWDEN,3.403846,3.444016,2019-12-02,None,2019-12-02
9,484971,484971,2019-09-22,UA,UA_CODESHARE,UA,3503,YX,N651RW,3503,11618,EWR,"Newark, NJ",11433,DTW,"Detroit, MI",1400,1446.0,46.0,16.0,1502.0,1622.0,13.0,1557,1635.0,38.0,0.0,0.0,N,117.0,109.0,80.0,1.0,488.0,9.0,0.0,0.0,0.0,29.0,NaN,NaN,NaN,9,15,Short,366.000000,MI,0.019901,1,EWRDTW,2.369620,9.017267,2019-09-15,None,2019-09-15

In [223]:
def weather(x):
    r = []
    for i in x.index:
        params = {'location': x['origin_city_name'][i],'startDateTime': x['fl_date'][i],'endDateTime': x['fl_date'][i]}
        weather = re.get(f'https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/weatherdata/history?aggregateHours=24&combinationMethod=aggregate&maxStations=-1&maxDistance=-1&contentType=json&unitGroup=metric&locationMode=single&key={ApiKey}&dataElements=default&',params=params)
        z = weather.json()
        r.append(z)
    return r

In [215]:
Test['fl_date0'] = Test['fl_date_previous'].apply(lambda x: x.date().strftime('%Y-%m-%d'))

In [224]:
l = weather(Test)

In [232]:
t = []
for i in l:
    t.append(i['location']['values'])

In [233]:
y = pd.DataFrame(t)

In [240]:
from itertools import chain

In [242]:
y = pd.DataFrame(list(chain.from_iterable(t)))

In [255]:
weather_data = pd.concat([Test,y],axis = 1)

In [253]:
Test.drop(columns=['index','Unnamed: 0'],inplace=True)

In [258]:
pd.DataFrame.to_csv(weather_data,'weather_data.csv',index=False)

In [250]:
Test.reset_index(inplace=True)

In [247]:
weather_data = pd.join

,Unnamed: 0,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,month,hour,haul,flight_speed,state,proportional_activity,dummydelay,route,mean delay for route,mean delay based on air carrier,fl_date_previous,fl_date0
671530,671530,2018-09-23,AS,AS_CODESHARE,AS,2084,QX,N436QX,2084,13264,MFR,"Medford, OR",14057,PDX,"Portland, OR",1935,1927.0,-8.0,11.0,1938.0,2024.0,7.0,2032,2031.0,-1.0,0.0,0.0,N,57.0,64.0,46.0,1.0,222.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,19,Short,289.565217,OR,0.001152,0,MFRPDX,-1.303665,0.429957,2018-09-16,2018-09-16
576677,576677,2019-09-08,UA,UA_CODESHARE,UA,3923,ZW,N426AW,3923,10257,ALB,"Albany, NY",12264,IAD,"Washington, DC",1445,1439.0,-6.0,9.0,1448.0,1549.0,3.0,1618,1552.0,-26.0,0.0,0.0,N,93.0,73.0,61.0,1.0,325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,14,Short,319.672131,DC,0.002162,0,ALBIAD,19.194805,9.017267,2019-09-01,2019-09-01
458132,458132,2019-12-30,AA,AA_CODESHARE,AA,3413,MQ,N220NN,3413,12992,LIT,"Little Rock, AR",11298,DFW,"Dallas/Fort Worth, TX",2013,2016.0,3.0,21.0,2037.0,2141.0,9.0,2141,2150.0,9.0,0.0,0.0,N,88.0,94.0,64.0,1.0,304.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,20,Short,285.000000,TX,0.001865,1,LITDFW,7.461538,6.393277,2019-12-23,2019-12-23
324870,324870,2018-01-31,AA,AA_CODESHARE,AA,4760,YX,N403YX,4760,11278,DCA,"Washington, DC",12953,LGA,"New York, NY",1900,1854.0,-6.0,33.0,1927.0,2011.0,13.0,2039,2024.0,-15.0,0.0,0.0,N,99.0,90.0,44.0,1.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,19,Short,291.818182,NY,0.017513,0,DCALGA,13.448276,6.393277,2018-01-24,2018-01-24
504388,504388,2018-06-13,UA,UA_CODESHARE,UA,5539,OO,N144SY,5539,14771,SFO,"San Francisco, CA",14869,SLC,"Salt Lake City, UT",900,855.0,-5.0,17.0,912.0,1141.0,5.0,1202,1146.0,-16.0,0.0,0.0,N,122.0,111.0,89.0,1.0,599.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,9,Short,403.820225,UT,0.022608,0,SFOSLC,7.478386,9.017267,2018-06-06,2018-06-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218259,218259,2019-12-20,WN,WN,WN,2084,WN,N712SW,2084,10821,BWI,"Baltimore, MD",10693,BNA,"Nashville, TN",1920,1942.0,22.0,13.0,1955.0,2031.0,4.0,2015,2035.0,20.0,0.0,0.0,N,115.0,113.0,96.0,1.0,587.0,15.0,0.0,0.0,0.0,5.0,NaN,NaN,NaN,12,19,Short,366.875000,TN,0.013186,1,BWIBNA,-0.552486,3.444016,2019-12-13,2019-12-13
250443,250443,2018-07-15,WN,WN,WN,3149,WN,N937WN,3149,14893,SMF,"Sacramento, CA",15016,STL,"St. Louis, MO",910,905.0,-5.0,10.0,915.0,1433.0,3.0,1445,1436.0,-9.0,0.0,0.0,N,215.0,211.0,198.0,1.0,1679.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,9,Medium,508.787879,MO,0.006941,0,SMFSTL,-3.720000,3.444016,2018-07-08,2018-07-08
354329,354329,2018-08-09,AA,AA,AA,2042,AA,N973UY,2042,14771,SFO,"San Francisco, CA",14107,PHX,"Phoenix, AZ",550,549.0,-1.0,12.0,601.0,736.0,16.0,758,752.0,-6.0,0.0,0.0,N,128.0,123.0,95.0,1.0,651.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,6,Short,411.157895,AZ,0.022608,0,SFOPHX,7.534632,6.393277,2018-08-02,2018-08-02
573121,573121,2019-12-08,UA,UA_CODESHARE,UA,4552,G7,N153GJ,4552,12451,JAX,"Jacksonville, FL",13930,ORD,"Chicago, IL",730,727.0,-3.0,29.0,756.0,900.0,7.0,912,907.0,-5.0,0.0,0.0,N,162.0,160.0,124.0,1.0,864.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,7,Short,418.064516,IL,0.004443,0,JAXORD,3.946524,9.017267,2019-12-01,2019-12-01
351445,351445,2019-05-25,AA,AA_CODESHARE,AA,4035,MQ,N271NN,4035,11298,DFW,"Dallas/Fort Worth, TX",11003,CID,"Cedar Rapids/Iowa City, IA",1030,1024.0,-6.0,13.0,1037.0,1209.0,6.0,1232,1215.0,-17.0,0.0,0.0,N,122.0,111.0,92.0,1.0,685.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,10,Short,446.739130,IA,0.036820,0,DFWCID,0.500000,6.393277,2019-05-18,2019-05-18

In [178]:
random[0]['origin_city_name']

KeyError: 0

In [143]:
df = random.apply(lambda x: weather(x))

KeyError: 'origin_city_name'

In [141]:
random

,Unnamed: 0,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,month,hour,haul,flight_speed,state,proportional_activity,dummydelay,route,mean delay for route,mean delay based on air carrier,fl_date_previous,conditions
671530,671530,2018-09-23,AS,AS_CODESHARE,AS,2084,QX,N436QX,2084,13264,MFR,"Medford, OR",14057,PDX,"Portland, OR",1935,1927.0,-8.0,11.0,1938.0,2024.0,7.0,2032,2031.0,-1.0,0.0,0.0,N,57.0,64.0,46.0,1.0,222.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,19,Short,289.565217,OR,0.001152,0,MFRPDX,-1.303665,0.429957,2018-09-16,None
576677,576677,2019-09-08,UA,UA_CODESHARE,UA,3923,ZW,N426AW,3923,10257,ALB,"Albany, NY",12264,IAD,"Washington, DC",1445,1439.0,-6.0,9.0,1448.0,1549.0,3.0,1618,1552.0,-26.0,0.0,0.0,N,93.0,73.0,61.0,1.0,325.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,14,Short,319.672131,DC,0.002162,0,ALBIAD,19.194805,9.017267,2019-09-01,None
458132,458132,2019-12-30,AA,AA_CODESHARE,AA,3413,MQ,N220NN,3413,12992,LIT,"Little Rock, AR",11298,DFW,"Dallas/Fort Worth, TX",2013,2016.0,3.0,21.0,2037.0,2141.0,9.0,2141,2150.0,9.0,0.0,0.0,N,88.0,94.0,64.0,1.0,304.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,20,Short,285.000000,TX,0.001865,1,LITDFW,7.461538,6.393277,2019-12-23,None
324870,324870,2018-01-31,AA,AA_CODESHARE,AA,4760,YX,N403YX,4760,11278,DCA,"Washington, DC",12953,LGA,"New York, NY",1900,1854.0,-6.0,33.0,1927.0,2011.0,13.0,2039,2024.0,-15.0,0.0,0.0,N,99.0,90.0,44.0,1.0,214.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,19,Short,291.818182,NY,0.017513,0,DCALGA,13.448276,6.393277,2018-01-24,None
504388,504388,2018-06-13,UA,UA_CODESHARE,UA,5539,OO,N144SY,5539,14771,SFO,"San Francisco, CA",14869,SLC,"Salt Lake City, UT",900,855.0,-5.0,17.0,912.0,1141.0,5.0,1202,1146.0,-16.0,0.0,0.0,N,122.0,111.0,89.0,1.0,599.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,9,Short,403.820225,UT,0.022608,0,SFOSLC,7.478386,9.017267,2018-06-06,None
83739,83739,2018-12-09,DL,DL_CODESHARE,DL,5906,YX,N215JQ,5906,11066,CMH,"Columbus, OH",12478,JFK,"New York, NY",1758,1755.0,-3.0,17.0,1812.0,1936.0,14.0,2005,1950.0,-15.0,0.0,0.0,N,127.0,115.0,84.0,1.0,483.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,18,Short,345.000000,NY,0.006125,0,CMHJFK,-0.336449,2.490683,2018-12-02,None
85375,85375,2018-01-14,DL,DL_CODESHARE,DL,6059,YX,N216JQ,6059,10721,BOS,"Boston, MA",12953,LGA,"New York, NY",1000,950.0,-10.0,21.0,1011.0,1055.0,4.0,1133,1059.0,-34.0,0.0,0.0,N,93.0,69.0,44.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,Short,250.909091,NY,0.018905,0,BOSLGA,8.193511,2.490683,2018-01-07,None
491929,491929,2018-11-02,UA,UA_CODESHARE,UA,4941,C5,N14186,4941,11618,EWR,"Newark, NJ",13244,MEM,"Memphis, TN",1940,1934.0,-6.0,24.0,1958.0,2150.0,6.0,2153,2156.0,3.0,0.0,0.0,N,193.0,202.0,172.0,1.0,946.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,19,Short,330.000000,TN,0.019901,0,EWRMEM,25.009804,9.017267,2018-10-26,None
275868,275868,2019-12-09,WN,WN,WN,2575,WN,N8638A,2575,13232,MDW,"Chicago, IL",11292,DEN,"Denver, CO",1730,1745.0,15.0,11.0,1756.0,1909.0,10.0,1905,1919.0,14.0,0.0,0.0,N,155.0,154.0,133.0,1.0,895.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,17,Short,403.759398,CO,0.010570,1,MDWDEN,3.403846,3.444016,2019-12-02,None
484971,484971,2019-09-22,UA,UA_CODESHARE,UA,3503,YX,N651RW,3503,11618,EWR,"Newark, NJ",11433,DTW,"Detroit, MI",1400,1446.0,46.0,16.0,1502.0,1622.0,13.0,1557,1635.0,38.0,0.0,0.0,N,117.0,109.0,80.0,1.0,488.0,9.0,0.0,0.0,0.0,29.0,NaN,NaN,NaN,9,15,Short,366.000000,MI,0.019901,1,EWRDTW,2.369620,9.017267,2019-09-15,None

In [136]:
i

[{'temp': 17.4,
  'maxt': 23.1,
  'visibility': 14.5,
  'wspd': 20.4,
  'datetimeStr': '2018-06-15T00:00:00-04:00',
  'heatindex': None,
  'cloudcover': 74.8,
  'mint': 13.8,
  'datetime': 1529020800000,
  'precip': 0.64,
  'weathertype': 'Mist, Light Drizzle, Light Rain',
  'snowdepth': 0.0,
  'humidity': 68.81,
  'wgust': 44.0,
  'conditions': 'Rain, Partially cloudy',
  'windchill': None},
 {'temp': 17.4,
  'maxt': 23.1,
  'visibility': 14.5,
  'wspd': 20.4,
  'datetimeStr': '2018-06-15T00:00:00-04:00',
  'heatindex': None,
  'cloudcover': 74.8,
  'mint': 13.8,
  'datetime': 1529020800000,
  'precip': 0.64,
  'weathertype': 'Mist, Light Drizzle, Light Rain',
  'snowdepth': 0.0,
  'humidity': 68.81,
  'wgust': 44.0,
  'conditions': 'Rain, Partially cloudy',
  'windchill': None}]

In [97]:
random['conditions'] = random['origin_city_name'].apply(lambda x: weather(x))

<ipython-input-97-880c8cea074f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  random['conditions'] = random['origin_city_name'].apply(lambda x: weather(x))

In [99]:
i

[{'temp': 16.9,
  'maxt': 23.8,
  'visibility': 16.0,
  'wspd': 22.3,
  'datetimeStr': '2018-06-15T00:00:00-07:00',
  'heatindex': None,
  'cloudcover': 11.5,
  'mint': 9.9,
  'datetime': 1529020800000,
  'precip': 0.0,
  'weathertype': 'Mist, Fog, Light Rain',
  'snowdepth': 0.0,
  'humidity': 49.09,
  'wgust': 42.5,
  'conditions': 'Clear',
  'windchill': None},
 {'temp': 17.4,
  'maxt': 23.1,
  'visibility': 14.5,
  'wspd': 20.4,
  'datetimeStr': '2018-06-15T00:00:00-04:00',
  'heatindex': None,
  'cloudcover': 74.8,
  'mint': 13.8,
  'datetime': 1529020800000,
  'precip': 0.64,
  'weathertype': 'Mist, Light Drizzle, Light Rain',
  'snowdepth': 0.0,
  'humidity': 68.81,
  'wgust': 44.0,
  'conditions': 'Rain, Partially cloudy',
  'windchill': None},
 {'temp': 28.5,
  'maxt': 33.5,
  'visibility': 15.3,
  'wspd': 16.3,
  'datetimeStr': '2018-06-15T00:00:00-05:00',
  'heatindex': 37.7,
  'cloudcover': 34.8,
  'mint': 22.9,
  'datetime': 1529020800000,
  'precip': 0.0,
  'weathertype': '',
  'snowdepth': 0.0,
  'humidity': 73.6,
  'wgust': None,
  'conditions': 'Partially cloudy',
  'windchill': None},
 {'temp': 24.7,
  'maxt': 28.8,
  'visibility': 16.0,
  'wspd': 27.7,
  'datetimeStr': '2018-06-15T00:00:00-04:00',
  'heatindex': 27.7,
  'cloudcover': 41.3,
  'mint': 19.8,
  'datetime': 1529020800000,
  'precip': 0.0,
  'weathertype': '',
  'snowdepth': 0.0,
  'humidity': 43.08,
  'wgust': 40.7,
  'conditions': 'Partially cloudy',
  'windchill': None},
 {'temp': 15.6,
  'maxt': 18.2,
  'visibility': 15.3,
  'wspd': 35.2,
  'datetimeStr': '2018-06-15T00:00:00-07:00',
  'heatindex': None,
  'cloudcover': 43.8,
  'mint': 13.4,
  'datetime': 1529020800000,
  'precip': 0.0,
  'weathertype': 'Mist, Smoke Or Haze',
  'snowdepth': 0.0,
  'humidity': 70.18,
  'wgust': 48.1,
  'conditions': 'Partially cloudy',
  'windchill': None},
 {'temp': 23.4,
  'maxt': 29.5,
  'visibility': 16.0,
  'wspd': 9.2,
  'datetimeStr': '2018-06-15T00:00:00-04:00',
  'heatindex': 28.6,
  'cloudcover': 42.9,
  'mint': 16.1,
  'datetime': 1529020800000,
  'precip': 0.0,
  'weathertype': '',
  'snowdepth': 0.0,
  'humidity': 56.84,
  'wgust': None,
  'conditions': 'Partially cloudy',
  'windchill': None},
 {'temp': 14.7,
  'maxt': 17.3,
  'visibility': 15.7,
  'wspd': 18.0,
  'datetimeStr': '2018-06-15T00:00:00-04:00',
  'heatindex': None,
  'cloudcover': 75.4,
  'mint': 12.3,
  'datetime': 1529020800000,
  'precip': 0.0,
  'weathertype': 'Mist, Light Rain',
  'snowdepth': 0.0,
  'humidity': 80.66,
  'wgust': None,
  'conditions': 'Overcast',
  'windchill': None},
 {'temp': 22.1,
  'maxt': 26.4,
  'visibility': 16.0,
  'wspd': 33.3,
  'datetimeStr': '2018-06-15T00:00:00-04:00',
  'heatindex': None,
  'cloudcover': 48.8,
  'mint': 18.3,
  'datetime': 1529020800000,
  'precip': 0.0,
  'weathertype': '',
  'snowdepth': 0.0,
  'humidity': 46.75,
  'wgust': 44.1,
  'conditions': 'Partially cloudy',
  'windchill': None},
 {'temp': 25.4,
  'maxt': 31.4,
  'visibility': 16.0,
  'wspd': 23.3,
  'datetimeStr': '2018-06-15T00:00:00-05:00',
  'heatindex': 32.6,
  'cloudcover': 54.9,
  'mint': 18.5,
  'datetime': 1529020800000,
  'precip': 0.0,
  'weathertype': '',
  'snowdepth': 0.0,
  'humidity': 55.12,
  'wgust': 31.7,
  'conditions': 'Partially cloudy',
  'windchill': None},
 {'temp': 22.1,
  'maxt': 26.4,
  'visibility': 16.0,
  'wspd': 33.3,
  'datetimeStr': '2018-06-15T00:00:00-04:00',
  'heatindex': None,
  'cloudcover': 48.8,
  'mint': 18.3,
  'datetime': 1529020800000,
  'precip': 0.0,
  'weathertype': '',
  'snowdepth': 0.0,
  'humidity': 46.75,
  'wgust': 44.1,
  'conditions': 'Partially cloudy',
  'windchill': None},
 'Clear',
 'Rain, Partially cloudy',
 'Partially cloudy',
 'Partially cloudy',
 'Partially cloudy',
 'Partially cloudy',
 'Overcast',
 'Partially cloudy',
 'Partially cloudy',
 'Partially cloudy']

In [94]:
r = pd.DataFrame(i)

In [95]:
r

,temp,maxt,visibility,wspd,datetimeStr,heatindex,cloudcover,mint,datetime,precip,weathertype,snowdepth,humidity,wgust,conditions,windchill
0,16.9,23.8,16.0,22.3,2018-06-15T00:00:00-07:00,NaN,11.5,9.9,1529020800000,0.00,"Mist, Fog, Light Rain",0.0,49.09,42.5,Clear,None
1,17.4,23.1,14.5,20.4,2018-06-15T00:00:00-04:00,NaN,74.8,13.8,1529020800000,0.64,"Mist, Light Drizzle, Light Rain",0.0,68.81,44.0,"Rain, Partially cloudy",None
2,28.5,33.5,15.3,16.3,2018-06-15T00:00:00-05:00,37.7,34.8,22.9,1529020800000,0.00,,0.0,73.60,NaN,Partially cloudy,None
3,24.7,28.8,16.0,27.7,2018-06-15T00:00:00-04:00,27.7,41.3,19.8,1529020800000,0.00,,0.0,43.08,40.7,Partially cloudy,None
4,15.6,18.2,15.3,35.2,2018-06-15T00:00:00-07:00,NaN,43.8,13.4,1529020800000,0.00,"Mist, Smoke Or Haze",0.0,70.18,48.1,Partially cloudy,None
5,23.4,29.5,16.0,9.2,2018-06-15T00:00:00-04:00,28.6,42.9,16.1,1529020800000,0.00,,0.0,56.84,NaN,Partially cloudy,None
6,14.7,17.3,15.7,18.0,2018-06-15T00:00:00-04:00,NaN,75.4,12.3,1529020800000,0.00,"Mist, Light Rain",0.0,80.66,NaN,Overcast,None
7,22.1,26.4,16.0,33.3,2018-06-15T00:00:00-04:00,NaN,48.8,18.3,1529020800000,0.00,,0.0,46.75,44.1,Partially cloudy,None
8,25.4,31.4,16.0,23.3,2018-06-15T00:00:00-05:00,32.6,54.9,18.5,1529020800000,0.00,,0.0,55.12,31.7,Partially cloudy,None
9,22.1,26.4,16.0,33.3,2018-06-15T00:00:00-04:00,NaN,48.8,18.3,1529020800000,0.00,,0.0,46.75,44.1,Partially cloudy,None

In [53]:
#X2['origin_city_name'].apply(lambda x: print(x))

In [54]:
#X1['origin_city_name'].apply(lambda x: print(x))

In [42]:
Z1 = pd.merge(Z,df,how='inner',)

       fl_date fl_date_previous
0   2018-06-15       2018-06-08
1   2019-07-30       2019-07-23
2   2018-07-17       2018-07-10
3   2019-08-04       2019-07-28
4   2019-05-30       2019-05-23
..         ...              ...
725 2019-01-19       2019-01-12
726 2019-06-05       2019-05-29
727 2018-01-27       2018-01-20
728 2018-12-24       2018-12-17
729 2018-09-30       2018-09-23

[730 rows x 2 columns]

In [20]:
z = weather.json()

In [84]:
JSON(z)

In [89]:
z['location']['values'][-1]

{'temp': 25.1,
 'maxt': 29.6,
 'visibility': 14.2,
 'wspd': 19.3,
 'datetimeStr': '2018-06-15T00:00:00-04:00',
 'heatindex': 30.0,
 'cloudcover': 66.9,
 'mint': 21.2,
 'datetime': 1529020800000,
 'precip': 0.0,
 'weathertype': 'Mist, Fog',
 'snowdepth': 0.0,
 'humidity': 73.75,
 'wgust': 33.5,
 'conditions': 'Partially cloudy',
 'windchill': None}

In [23]:
z

{'columns': {'temp': {'id': 'temp',
   'name': 'Temperature',
   'type': 2,
   'unit': 'degC'},
  'maxt': {'id': 'maxt',
   'name': 'Maximum Temperature',
   'type': 2,
   'unit': 'degC'},
  'visibility': {'id': 'visibility',
   'name': 'Visibility',
   'type': 2,
   'unit': 'km'},
  'wspd': {'id': 'wspd', 'name': 'Wind Speed', 'type': 2, 'unit': 'kph'},
  'heatindex': {'id': 'heatindex',
   'name': 'Heat Index',
   'type': 2,
   'unit': 'degC'},
  'cloudcover': {'id': 'cloudcover',
   'name': 'Cloud Cover',
   'type': 2,
   'unit': '%'},
  'mint': {'id': 'mint',
   'name': 'Minimum Temperature',
   'type': 2,
   'unit': 'degC'},
  'datetime': {'id': 'datetime', 'name': 'Date time', 'type': 3, 'unit': None},
  'precip': {'id': 'precip', 'name': 'Precipitation', 'type': 2, 'unit': 'mm'},
  'weathertype': {'id': 'weathertype',
   'name': 'Weather Type',
   'type': 1,
   'unit': None},
  'snowdepth': {'id': 'snowdepth',
   'name': 'Snow Depth',
   'type': 2,
   'unit': 'cm'},
  'name': {'id': 'name', 'name': 'Name', 'type': 1, 'unit': None},
  'humidity': {'id': 'humidity',
   'name': 'Relative Humidity',
   'type': 2,
   'unit': '%'},
  'wgust': {'id': 'wgust', 'name': 'Wind Gust', 'type': 2, 'unit': 'kph'},
  'conditions': {'id': 'conditions',
   'name': 'Conditions',
   'type': 1,
   'unit': None},
  'windchill': {'id': 'windchill',
   'name': 'Wind Chill',
   'type': 2,
   'unit': 'degC'}},
 'remainingCost': 0,
 'queryCost': 8,
 'messages': None,
 'location': {'stationContributions': None,
  'values': [{'temp': 24.8,
    'maxt': 30.7,
    'visibility': 15.9,
    'wspd': 9.8,
    'datetimeStr': '2018-06-08T00:00:00-04:00',
    'heatindex': 32.6,
    'cloudcover': 60.6,
    'mint': 18.7,
    'datetime': 1528416000000,
    'precip': 0.0,
    'weathertype': 'Mist',
    'snowdepth': 0.0,
    'humidity': 75.93,
    'wgust': None,
    'conditions': 'Partially cloudy',
    'windchill': None},
   {'temp': 25.5,
    'maxt': 30.9,
    'visibility': 15.7,
    'wspd': 9.6,
    'datetimeStr': '2018-06-09T00:00:00-04:00',
    'heatindex': 32.2,
    'cloudcover': 57.2,
    'mint': 20.0,
    'datetime': 1528502400000,
    'precip': 0.0,
    'weathertype': 'Mist',
    'snowdepth': 0.0,
    'humidity': 76.05,
    'wgust': None,
    'conditions': 'Partially cloudy',
    'windchill': None},
   {'temp': 25.9,
    'maxt': 32.3,
    'visibility': 15.7,
    'wspd': 11.9,
    'datetimeStr': '2018-06-10T00:00:00-04:00',
    'heatindex': 35.6,
    'cloudcover': 48.6,
    'mint': 19.5,
    'datetime': 1528588800000,
    'precip': 0.08,
    'weathertype': 'Mist, Light Rain',
    'snowdepth': 0.0,
    'humidity': 77.53,
    'wgust': None,
    'conditions': 'Rain, Partially cloudy',
    'windchill': None},
   {'temp': 22.9,
    'maxt': 29.0,
    'visibility': 14.6,
    'wspd': 24.8,
    'datetimeStr': '2018-06-11T00:00:00-04:00',
    'heatindex': 32.9,
    'cloudcover': 80.5,
    'mint': 18.4,
    'datetime': 1528675200000,
    'precip': 15.99,
    'weathertype': 'Mist, Thunderstorm, Rain, Heavy Rain, Light Rain',
    'snowdepth': 0.0,
    'humidity': 89.36,
    'wgust': 41.0,
    'conditions': 'Rain, Overcast',
    'windchill': None},
   {'temp': 18.6,
    'maxt': 21.1,
    'visibility': 12.8,
    'wspd': 18.7,
    'datetimeStr': '2018-06-12T00:00:00-04:00',
    'heatindex': None,
    'cloudcover': 93.3,
    'mint': 16.9,
    'datetime': 1528761600000,
    'precip': 4.83,
    'weathertype': 'Drizzle, Mist, Heavy Drizzle, Light Drizzle, Rain, Heavy Rain, Light Rain',
    'snowdepth': 0.0,
    'humidity': 96.29,
    'wgust': 35.3,
    'conditions': 'Rain, Overcast',
    'windchill': None},
   {'temp': 23.5,
    'maxt': 28.5,
    'visibility': 13.6,
    'wspd': 15.4,
    'datetimeStr': '2018-06-13T00:00:00-04:00',
    'heatindex': 31.7,
    'cloudcover': 69.1,
    'mint': 19.2,
    'datetime': 1528848000000,
    'precip': 0.0,
    'weathertype': 'Mist, Light Drizzle',
    'snowdepth': 0.0,
    'humidity': 85.27,
    'wgust': None,
    'conditions': 'Partially cloudy',
    'windchill': None},
   {'temp': 26.3,
    'maxt': 31.4,
    'visibility': 15.9,
    'wspd': 10.6,
    'datetimeStr': '2018-06-14T00:00:00-04:00',
    'heatindex': 35.1,
    'cloudcover': 65.7,
    'mint': 21.2,
    'datetime': 1528934400000,
    'precip': 0.0,
    'weathertype': '',
    'snowdepth': 0.0,
    'humidity': 78.81,
    'wgust': None,
    'conditions': 'Partially cloudy',
    'windchill': None},
   {'temp': 25.1,
    'maxt': 29.6,
    'visibility': 14.2,
    'wspd': 19.3,
    'datetimeStr': '2018-06-15T00:00:00-04:00',
    'heatindex': 30.0,
    'cloudcover': 66.9,
    'mint': 21.2,
    'datetime': 1529020800000,
    'precip': 0.0,
    'weathertype': 'Mist, Fog',
    'snowdepth': 0.0,
    'humidity': 73.75,
    'wgust': 33.5,
    'conditions': 'Partially cloudy',
    'windchill': None}],
  'id': 'Raleigh/Durham, NC',
  'address': 'Durham Rd, Raleigh, NC 27614, United States',
  'name': 'Durham Rd, Raleigh, NC 27614, United States',
  'index': 0,
  'latitude': 35.9869,
  'longitude': -78.6686,
  'distance': 0.0,
  'time': 0.0,
  'tz': 'America/New_York',
  'currentConditions': None,
  'alerts': None}}