In [1]:
import pandas as pd
import psycopg2

Building a function to obtain data using SQL queries and postgres module

In [2]:
def queryreturn(query):
    con = psycopg2.connect(database="mid_term_project", user="lhl_student", password="lhl_student", host="mid-term-project.ca2jkepgjpne.us-east-2.rds.amazonaws.com", port="5432")
    cur = con.cursor()
    cur.execute(query)
    rows = cur.fetchall()
    df = pd.DataFrame(rows)
    con.close()
    return df

In [9]:
query = 'SELECT * FROM passengers ORDER BY RANDOM() LIMIT 700000'

passengers = queryreturn(query)

In [4]:
query = 'SELECT * FROM flights ORDER BY RANDOM() LIMIT 700000'

flights = queryreturn(query)

In [9]:
query = 'SELECT * FROM fuel_comsumption LIMIT 700000'

fuel_consumption = queryreturn(query)

In [3]:
query = 'SELECT * FROM flights_test LIMIT 700000'

In [4]:
flights_test = queryreturn(query)

In [12]:
flights_test = flights_test[flights_test['fl_date']<= '2020-01-07']

In [13]:
flights_test

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,dest_airport_id,dest,dest_city_name,crs_dep_time,crs_arr_time,dup,crs_elapsed_time,flights,distance
0,2020-01-01,WN,WN,WN,5888,WN,N951WN,5888,13891,ONT,"Ontario, CA",14771,SFO,"San Francisco, CA",1810,1945,N,95,1,363
1,2020-01-01,WN,WN,WN,6276,WN,N467WN,6276,13891,ONT,"Ontario, CA",14771,SFO,"San Francisco, CA",1150,1320,N,90,1,363
2,2020-01-01,WN,WN,WN,4598,WN,N7885A,4598,13891,ONT,"Ontario, CA",14831,SJC,"San Jose, CA",2020,2130,N,70,1,333
3,2020-01-01,WN,WN,WN,4761,WN,N551WN,4761,13891,ONT,"Ontario, CA",14831,SJC,"San Jose, CA",1340,1455,N,75,1,333
4,2020-01-01,WN,WN,WN,5162,WN,N968WN,5162,13891,ONT,"Ontario, CA",14831,SJC,"San Jose, CA",915,1035,N,80,1,333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150618,2020-01-07,DL,DL_CODESHARE,DL,4813,9E,N605LR,4813,11433,DTW,"Detroit, MI",12478,JFK,"New York, NY",1755,1952,N,117,1,509
150619,2020-01-07,DL,DL_CODESHARE,DL,4814,9E,N919XJ,4814,11996,GSP,"Greer, SC",12953,LGA,"New York, NY",600,759,N,119,1,610
150620,2020-01-07,DL,DL_CODESHARE,DL,4815,9E,N936XJ,4815,10397,ATL,"Atlanta, GA",15919,XNA,"Fayetteville, AR",1715,1816,N,121,1,589
150621,2020-01-07,DL,DL_CODESHARE,DL,4815,9E,N936XJ,4815,15919,XNA,"Fayetteville, AR",10397,ATL,"Atlanta, GA",1851,2145,N,114,1,589
150622,2020-01-07,DL,DL_CODESHARE,DL,4816,9E,N917XJ,4816,14321,PWM,"Portland, ME",12953,LGA,"New York, NY",600,741,N,101,1,269

In [14]:
flights_test['origin_city_name'].nunique()

356

Getting column names using csv files obtained from VS code SQL extension

In [6]:
flightscolumns = pd.read_csv('Columns/FlightsColumns.csv')

flights.columns = flightscolumns.columns.tolist()

In [11]:
passengerscolumns = pd.read_csv('Columns/PassengersColumns.csv')

passengers.columns = passengerscolumns.columns.tolist()

In [17]:
fuel_consumptioncolumns = pd.read_csv('FCColumns.csv')

fuel_consumption.columns = fuel_consumptioncolumns.columns.tolist()

In [6]:
flights_testcolumns = pd.read_csv('Columns/Flights_testColumns.csv')

flights_test.columns = flights_testcolumns.columns.tolist()

Saving the data as CSV files

In [12]:
pd.DataFrame.to_csv(flights,'flights.csv')

In [13]:
pd.DataFrame.to_csv(passengers,'passengers.csv')

In [22]:
pd.DataFrame.to_csv(fuel_consumption,'fuel_consumption.csv')